# Generated by Django 3.2 on 2021-11-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20211107_0201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productpictures',
            table='product_pictures',
        ),
    ]
